# 配置注册中心的地址
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: chenoj-backend-user-service
          uri: lb://chenoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: chenoj-backend-judge-service
          uri: lb://chenoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: chenoj-backend-question-service
          uri: lb://chenoj-backend-question-service
          predicates:
            - Path=/api/question/**
  application:
    name: chenoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
# 给网关配置集中管理接口文档
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2